name: socko
description: Socket chat for CPT_S 455
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  http: ^0.13.5
  mobx: ^2.1.1
  provider: ^6.0.4
  flutter_mobx: ^2.0.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.7
flutter:
  uses-material-design: false